language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
install:
  - travis_retry composer install --no-interaction
script:
  - composer cs
  - if [[ "${TRAVIS_PHP_VERSION:0:3}" != "7.2" ]]; then composer test:standard; fi
  - if [[ "${TRAVIS_PHP_VERSION:0:3}" == "7.2" ]]; then composer test:all -- --coverage-clover clover.xml; fi
after_success:
  - if [[ "${TRAVIS_PHP_VERSION:0:3}" == "7.2" ]]; then travis_retry php vendor/bin/php-coveralls -v --coverage_clover clover.xml --json_path coveralls-upload.json; fi
